apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demoapp
  labels:
    app: python-demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-demoapp
  template:
    metadata:
      labels:
        app: python-demoapp
    spec:
      containers:
      - name: python-demoapp
        image: yasdevsec/python-demoapp:v3
        ports:
        - containerPort: 5000
