apiVersion: v1
kind: Service
metadata:
  name: python-demoapp
  labels:
    app: python-demoapp
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    app: python-demoapp
