global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      # Sur Linux, l'hôte Docker est souvent 172.17.0.1
      - targets: ['172.17.0.1:8080']
