global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # (optionnel) si un jour ton app expose /metrics et vit dans le même compose :
  # - job_name: "demoapp"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["app:5000"]
