---
- hosts: demo
  become: yes
  tasks:
    - name: Ensure APT cache is fresh
      apt:
        update_cache: yes
      tags: [deps]

    - name: Ensure Docker engine is installed
      apt:
        name: docker.io
        state: present
      tags: [deps]

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop & remove old container (if any)
      shell: docker rm -f demoapp || true
      changed_when: false

    - name: Run container from locally built image
      shell: >
        docker run -d --restart unless-stopped --name demoapp
        -p 5000:5000 --pull=never {{ image | default('demoapp:latest') }}
      args:
        warn: false
      changed_when: true
